//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHM.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IHM.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured.
        /// </summary>
        internal static string Err_AnErrorOccured {
            get {
                return ResourceManager.GetString("Err_AnErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must give at least one url.
        /// </summary>
        internal static string Err_OneUrlMinimum {
            get {
                return ResourceManager.GetString("Err_OneUrlMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must give a folder path.
        /// </summary>
        internal static string Err_UserMustGiveOneFolderPath {
            get {
                return ResourceManager.GetString("Err_UserMustGiveOneFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyze !.
        /// </summary>
        internal static string IHM_Btn_Analyze {
            get {
                return ResourceManager.GetString("IHM_Btn_Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string IHM_Btn_AnalyzeStop {
            get {
                return ResourceManager.GetString("IHM_Btn_AnalyzeStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change path.
        /// </summary>
        internal static string IHM_Btn_ChangePath {
            get {
                return ResourceManager.GetString("IHM_Btn_ChangePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Excel options :.
        /// </summary>
        internal static string IHM_Gb_ExcelOptions {
            get {
                return ResourceManager.GetString("IHM_Gb_ExcelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Youtube API options :.
        /// </summary>
        internal static string IHM_Gb_YoutubeOptions {
            get {
                return ResourceManager.GetString("IHM_Gb_YoutubeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Billiard separator :.
        /// </summary>
        internal static string IHM_Lbl_BilliardSeparator {
            get {
                return ResourceManager.GetString("IHM_Lbl_BilliardSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date format :.
        /// </summary>
        internal static string IHM_Lbl_DateFormat {
            get {
                return ResourceManager.GetString("IHM_Lbl_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration format :.
        /// </summary>
        internal static string IHM_Lbl_DurationFormat {
            get {
                return ResourceManager.GetString("IHM_Lbl_DurationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folder path :.
        /// </summary>
        internal static string IHM_Lbl_FolderPath {
            get {
                return ResourceManager.GetString("IHM_Lbl_FolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main youtube url page :.
        /// </summary>
        internal static string IHM_Lbl_MainYoutubeUrlPage {
            get {
                return ResourceManager.GetString("IHM_Lbl_MainYoutubeUrlPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Million separator :.
        /// </summary>
        internal static string IHM_Lbl_MillionSeparator {
            get {
                return ResourceManager.GetString("IHM_Lbl_MillionSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à State of process : waiting for user action.
        /// </summary>
        internal static string IHM_Lbl_StateOfProcess {
            get {
                return ResourceManager.GetString("IHM_Lbl_StateOfProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thousand separator :.
        /// </summary>
        internal static string IHM_Lbl_ThousandSeparator {
            get {
                return ResourceManager.GetString("IHM_Lbl_ThousandSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort videos by :.
        /// </summary>
        internal static string IHM_Lbl_VideoSortingChoice {
            get {
                return ResourceManager.GetString("IHM_Lbl_VideoSortingChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Youtube API Key :.
        /// </summary>
        internal static string IHM_Lbl_YoutubeAPIKey {
            get {
                return ResourceManager.GetString("IHM_Lbl_YoutubeAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à State of process :.
        /// </summary>
        internal static string ProcessState {
            get {
                return ResourceManager.GetString("ProcessState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à work finished.
        /// </summary>
        internal static string ProcessStateFinished {
            get {
                return ResourceManager.GetString("ProcessStateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à working.
        /// </summary>
        internal static string ProcessStateWorking {
            get {
                return ResourceManager.GetString("ProcessStateWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The datas have been saved in {0} Work done in {1}.
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyze canceled by user..
        /// </summary>
        internal static string UserAskForStop {
            get {
                return ResourceManager.GetString("UserAskForStop", resourceCulture);
            }
        }
    }
}
