//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHM.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VideosSorting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VideosSorting() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IHM.Properties.VideosSorting", typeof(VideosSorting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date creation (asc).
        /// </summary>
        internal static string DateCreationAsc {
            get {
                return ResourceManager.GetString("DateCreationAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date creation (desc).
        /// </summary>
        internal static string DateCreationDesc {
            get {
                return ResourceManager.GetString("DateCreationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration (asc).
        /// </summary>
        internal static string DurationAsc {
            get {
                return ResourceManager.GetString("DurationAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration (desc).
        /// </summary>
        internal static string DurationDesc {
            get {
                return ResourceManager.GetString("DurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name (asc).
        /// </summary>
        internal static string NameAsc {
            get {
                return ResourceManager.GetString("NameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name (desc).
        /// </summary>
        internal static string NameDesc {
            get {
                return ResourceManager.GetString("NameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not Sorted.
        /// </summary>
        internal static string NotSorted {
            get {
                return ResourceManager.GetString("NotSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number negatives feedback (asc).
        /// </summary>
        internal static string NumberNegativesFeedbackAsc {
            get {
                return ResourceManager.GetString("NumberNegativesFeedbackAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number negatives feedback (desc).
        /// </summary>
        internal static string NumberNegativesFeedbackDesc {
            get {
                return ResourceManager.GetString("NumberNegativesFeedbackDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number positives feedback (asc).
        /// </summary>
        internal static string NumberPositivesFeedbackAsc {
            get {
                return ResourceManager.GetString("NumberPositivesFeedbackAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number positives feedback (desc).
        /// </summary>
        internal static string NumberPositivesFeedbackDesc {
            get {
                return ResourceManager.GetString("NumberPositivesFeedbackDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number views (asc).
        /// </summary>
        internal static string NumberViewsAsc {
            get {
                return ResourceManager.GetString("NumberViewsAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number views (desc).
        /// </summary>
        internal static string NumberViewsDesc {
            get {
                return ResourceManager.GetString("NumberViewsDesc", resourceCulture);
            }
        }
    }
}
